#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Problem 3 step 3: event-level metrics, geographic accumulated rainfall,
duration maps, and scenario-comparison tables for S0-S5.

This script only consumes the Problem-3 scenario rainfields generated by step 2.
It does not regenerate half-hourly rainfields, retrain Problem-2 models, or
modify any Problem-2 env artifacts.
"""

from __future__ import annotations

import importlib.util
import math
import os
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

os.environ.setdefault("MPLCONFIGDIR", "/private/tmp/typhoon_rainfall_matplotlib_cache")
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

try:  # pragma: no cover - optional progress bar
    from tqdm import tqdm
except Exception:  # pragma: no cover
    tqdm = None


# =========================
# Paths and constants
# =========================

PROJECT_ROOT = Path(__file__).resolve().parents[1]

PROBLEM2_GEO_SCRIPT = PROJECT_ROOT / "scripts/24_geographic_backprojection_results.py"
PROBLEM2_EOF_MODEL_PATH = PROJECT_ROOT / "data/processed/problem2_env/problem2_eof_pca_model_env.npz"
PROBLEM2_GEO_NPZ_PATH = PROJECT_ROOT / "outputs/tables/problem2_env/problem2_final_geographic_fields.npz"
PROBLEM2_GEO_SUMMARY_PATH = PROJECT_ROOT / "outputs/tables/problem2_env/problem2_final_geographic_summary.csv"
PROBLEM2_GEO_TIMESERIES_PATH = PROJECT_ROOT / "outputs/tables/problem2_env/problem2_final_geographic_timeseries_metrics.csv"

SCENARIO_INPUT_PATH = PROJECT_ROOT / "data/processed/problem3_scenario_inputs.csv"
SCENARIO_SUMMARY_PATH = PROJECT_ROOT / "data/processed/problem3_scenario_summary.csv"
CALIBRATED_NPZ_PATH = PROJECT_ROOT / "data/processed/problem3/problem3_scenario_rainfields_calibrated.npz"
TIMESLICE_METRICS_PATH = PROJECT_ROOT / "data/processed/problem3/problem3_scenario_timeslice_metrics.csv"
GENERATION_QC_PATH = PROJECT_ROOT / "data/processed/problem3/problem3_scenario_generation_qc.csv"
TOPK_PATH = PROJECT_ROOT / "data/processed/problem3/problem3_scenario_topk_analogs.csv"

PROBLEM3_DATA_DIR = PROJECT_ROOT / "data/processed/problem3"
PROBLEM3_TABLE_DIR = PROJECT_ROOT / "outputs/tables/problem3"
PROBLEM3_FIGURE_DIR = PROJECT_ROOT / "outputs/figures/problem3"
PROBLEM3_REPORT_DIR = PROJECT_ROOT / "outputs/reports/problem3"

EVENT_METRICS_PATH = PROBLEM3_DATA_DIR / "problem3_scenario_event_metrics.csv"
RELATIVE_CHANGES_PATH = PROBLEM3_DATA_DIR / "problem3_scenario_relative_changes.csv"
GEOGRAPHIC_NPZ_PATH = PROBLEM3_DATA_DIR / "problem3_scenario_geographic_accum_duration.npz"
GEOGRAPHIC_TIMESERIES_PATH = PROBLEM3_DATA_DIR / "problem3_scenario_geographic_timeseries_metrics.csv"
STEP3_QC_PATH = PROBLEM3_DATA_DIR / "problem3_step3_metrics_qc.csv"
FINAL_COMPARISON_TABLE_PATH = PROBLEM3_TABLE_DIR / "problem3_final_scenario_comparison_table.csv"
SENSITIVITY_TABLE_PATH = PROBLEM3_TABLE_DIR / "problem3_sensitivity_interpretation_table.csv"
COMPACT_MAIN_TABLE_PATH = PROBLEM3_TABLE_DIR / "problem3_compact_main_table.tex"
PAPER_SCENARIO_LATEX_TABLE_PATH = PROBLEM3_TABLE_DIR / "problem3_paper_table_scenario_comparison_latex.tex"
REPORT_PATH = PROBLEM3_REPORT_DIR / "problem3_step3_event_metrics_report.md"

HALFHOUR_HOURS = 0.5
GEO_RES_DEG = 0.1
GEO_MARGIN_DEG = 8.0
EARTH_KM_PER_DEG = 111.32
AREA10_THRESHOLD = 10.0
AREA20_THRESHOLD = 20.0
SCENARIO_ORDER = ["S0", "S1", "S2", "S3", "S4", "S5"]
EXPECTED_COUNTS = {"S0": 421, "S1": 421, "S2": 421, "S3": 421, "S4": 647, "S5": 510}
EPS = 1e-12


# =========================
# General helpers
# =========================


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def ensure_dirs() -> None:
    for path in [PROBLEM3_DATA_DIR, PROBLEM3_TABLE_DIR, PROBLEM3_FIGURE_DIR, PROBLEM3_REPORT_DIR]:
        path.mkdir(parents=True, exist_ok=True)


def iter_progress(items: Iterable, total: Optional[int] = None, desc: str = "") -> Iterable:
    if tqdm is None:
        return items
    return tqdm(items, total=total, desc=desc)


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required input file is missing: {path}")


def load_problem2_geo_module():
    require_file(PROBLEM2_GEO_SCRIPT)
    spec = importlib.util.spec_from_file_location("problem2_geo_backprojection", PROBLEM2_GEO_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import Problem-2 geographic script: {PROBLEM2_GEO_SCRIPT}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def normalize_lon_180(lon: object) -> object:
    arr = np.asarray(lon, dtype=np.float64)
    out = ((arr + 180.0) % 360.0) - 180.0
    out = np.where(np.isclose(out, -180.0) & (arr > 0.0), 180.0, out)
    if np.isscalar(lon):
        return float(out)
    return out


def lon_diff_deg(lon: np.ndarray, center_lon: float) -> np.ndarray:
    return np.asarray(normalize_lon_180(lon - center_lon), dtype=np.float64)


def haversine_km(lon1: float, lat1: float, lon2: float, lat2: float) -> float:
    if not all(np.isfinite([lon1, lat1, lon2, lat2])):
        return float("nan")
    lat1_rad = math.radians(float(lat1))
    lat2_rad = math.radians(float(lat2))
    dlat = lat2_rad - lat1_rad
    dlon = math.radians(float(lon_diff_deg(np.asarray([lon2], dtype=float), float(lon1))[0]))
    a = math.sin(dlat / 2.0) ** 2 + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2.0) ** 2
    return float(6371.0 * 2.0 * math.asin(math.sqrt(max(0.0, min(1.0, a)))))


def area_of_mask(mask: np.ndarray, cell_area_1d: np.ndarray) -> float:
    valid = np.asarray(mask, dtype=bool)
    row_counts = np.count_nonzero(valid, axis=1).astype(np.float64)
    return float(np.sum(row_counts * np.asarray(cell_area_1d, dtype=np.float64)))


def weighted_field_sum(field: np.ndarray, cell_area_1d: np.ndarray) -> float:
    arr = np.nan_to_num(np.asarray(field, dtype=np.float64), nan=0.0, posinf=0.0, neginf=0.0)
    return float(np.sum(arr * np.asarray(cell_area_1d, dtype=np.float64)[:, None]))


def argmax_lon_lat(field: np.ndarray, lon_1d: np.ndarray, lat_1d: np.ndarray) -> Tuple[float, float, float]:
    arr = np.asarray(field, dtype=np.float64)
    if arr.size == 0 or not np.isfinite(arr).any():
        return np.nan, np.nan, np.nan
    clean = np.where(np.isfinite(arr), arr, -np.inf)
    iy, ix = np.unravel_index(int(np.argmax(clean)), clean.shape)
    return float(clean[iy, ix]), float(lon_1d[ix]), float(lat_1d[iy])


def pct_change(value: float, base: float) -> float:
    if not np.isfinite(base) or abs(float(base)) < EPS:
        return float("nan")
    if not np.isfinite(value):
        return float("nan")
    return float(100.0 * (float(value) - float(base)) / float(base))


def weighted_iou(mask: np.ndarray, base_mask: np.ndarray, cell_area_1d: np.ndarray) -> float:
    a = np.asarray(mask, dtype=bool)
    b = np.asarray(base_mask, dtype=bool)
    inter = area_of_mask(a & b, cell_area_1d)
    union = area_of_mask(a | b, cell_area_1d)
    if union <= 0.0:
        return float("nan")
    return float(inter / union)


def rainfall_centroid(
    field: np.ndarray,
    lon2d: np.ndarray,
    lat2d: np.ndarray,
    cell_area_1d: np.ndarray,
) -> Tuple[float, float]:
    arr = np.nan_to_num(np.asarray(field, dtype=np.float64), nan=0.0, posinf=0.0, neginf=0.0)
    weights = arr * np.asarray(cell_area_1d, dtype=np.float64)[:, None]
    total = float(np.sum(weights))
    if total <= 0.0:
        return float("nan"), float("nan")
    lon = float(np.sum(np.asarray(lon2d, dtype=np.float64) * weights) / total)
    lat = float(np.sum(np.asarray(lat2d, dtype=np.float64) * weights) / total)
    return lon, lat


def markdown_table(df: pd.DataFrame, columns: Optional[Sequence[str]] = None, max_rows: Optional[int] = None) -> str:
    view = df.copy()
    if columns is not None:
        view = view[list(columns)]
    if max_rows is not None:
        view = view.head(max_rows)
    if view.empty:
        return "_Empty table._"
    out = []
    header = "| " + " | ".join(map(str, view.columns)) + " |"
    sep = "| " + " | ".join(["---"] * len(view.columns)) + " |"
    out.extend([header, sep])
    for _, row in view.iterrows():
        vals = []
        for val in row:
            if isinstance(val, float):
                vals.append("" if pd.isna(val) else f"{val:.3f}")
            else:
                vals.append(str(val))
        out.append("| " + " | ".join(vals) + " |")
    return "\n".join(out)


def dominant_mode(series: pd.Series) -> str:
    if series.empty:
        return "NA"
    counts = series.dropna().astype(str).value_counts()
    if counts.empty:
        return "NA"
    return str(counts.index[0])


# =========================
# Input loading
# =========================


def load_inputs() -> Dict[str, object]:
    for path in [
        SCENARIO_INPUT_PATH,
        SCENARIO_SUMMARY_PATH,
        CALIBRATED_NPZ_PATH,
        TIMESLICE_METRICS_PATH,
        GENERATION_QC_PATH,
        TOPK_PATH,
        PROBLEM2_EOF_MODEL_PATH,
    ]:
        require_file(path)

    with np.load(CALIBRATED_NPZ_PATH, allow_pickle=True) as z:
        required = ["rainfields_calibrated_mmhr", "scenario_id", "scenario_name", "time", "lat", "lon", "lon_180", "WND", "PRES"]
        missing = [key for key in required if key not in z.files]
        if missing:
            raise RuntimeError(f"Problem-3 calibrated NPZ missing required arrays: {missing}")
        rain = np.asarray(z["rainfields_calibrated_mmhr"], dtype=np.float32)
        meta = {key: z[key] for key in required if key != "rainfields_calibrated_mmhr"}

    if rain.ndim != 3 or rain.shape[1:] != (201, 201):
        raise RuntimeError(f"Unexpected calibrated rainfield shape: {rain.shape}")
    if len(meta["scenario_id"]) != rain.shape[0]:
        raise RuntimeError("Calibrated rainfield time dimension and metadata length mismatch.")
    if np.isnan(rain).any() or np.isinf(rain).any() or np.any(rain < 0.0):
        raise RuntimeError("Calibrated rainfields contain NaN, Inf, or negative values.")

    with np.load(PROBLEM2_EOF_MODEL_PATH, allow_pickle=True) as z:
        if "x_front_km" not in z.files or "y_left_km" not in z.files:
            raise RuntimeError("Problem-2 EOF/PCA model artifact lacks x_front_km/y_left_km grid axes.")
        x_front_km = np.asarray(z["x_front_km"], dtype=np.float64)
        y_left_km = np.asarray(z["y_left_km"], dtype=np.float64)

    npz_meta = pd.DataFrame(
        {
            "field_index": np.arange(rain.shape[0], dtype=int),
            "scenario_id": np.asarray(meta["scenario_id"]).astype(str),
            "scenario_name": np.asarray(meta["scenario_name"]).astype(str),
            "time": np.asarray(meta["time"]).astype(str),
            "lat_npz": np.asarray(meta["lat"], dtype=float),
            "lon_npz": np.asarray(meta["lon"], dtype=float),
            "lon_180_npz": np.asarray(meta["lon_180"], dtype=float),
            "WND_npz": np.asarray(meta["WND"], dtype=float),
            "PRES_npz": np.asarray(meta["PRES"], dtype=float),
        }
    )
    npz_meta["time_dt"] = pd.to_datetime(npz_meta["time"], errors="coerce")
    if npz_meta["time_dt"].isna().any():
        raise RuntimeError("Calibrated NPZ metadata contains unparseable time values.")

    scenario_inputs = pd.read_csv(SCENARIO_INPUT_PATH)
    scenario_inputs["time"] = pd.to_datetime(scenario_inputs["time"], errors="coerce").dt.strftime("%Y-%m-%d %H:%M:%S")
    scenario_inputs["scenario_id"] = scenario_inputs["scenario_id"].astype(str)
    scenario_inputs["lon_180"] = normalize_lon_180(pd.to_numeric(scenario_inputs["lon"], errors="coerce").to_numpy(dtype=np.float64))
    needed = ["scenario_id", "scenario_name", "time", "lat", "lon", "lon_180", "WND", "PRES", "move_dir_deg"]
    missing_cols = [col for col in needed if col not in scenario_inputs.columns]
    if missing_cols:
        raise RuntimeError(f"Scenario input table missing required columns for geographic backprojection: {missing_cols}")

    canonical = npz_meta.merge(
        scenario_inputs[needed],
        on=["scenario_id", "scenario_name", "time"],
        how="left",
        validate="one_to_one",
    )
    if canonical["move_dir_deg"].isna().any():
        missing = canonical.loc[canonical["move_dir_deg"].isna(), ["scenario_id", "time"]].head()
        raise RuntimeError(f"Unable to align NPZ metadata with scenario_inputs for move_dir_deg. Examples: {missing.to_dict('records')}")
    canonical["lat"] = pd.to_numeric(canonical["lat"], errors="coerce")
    canonical["lon"] = pd.to_numeric(canonical["lon"], errors="coerce")
    canonical["lon_180"] = normalize_lon_180(pd.to_numeric(canonical["lon"], errors="coerce").to_numpy(dtype=np.float64))
    canonical["WND"] = pd.to_numeric(canonical["WND"], errors="coerce")
    canonical["PRES"] = pd.to_numeric(canonical["PRES"], errors="coerce")
    canonical["move_dir_deg"] = pd.to_numeric(canonical["move_dir_deg"], errors="coerce")
    if canonical[["lat", "lon_180", "move_dir_deg"]].isna().any().any():
        raise RuntimeError("Canonical scenario metadata has missing lat/lon_180/move_dir_deg values.")

    timeslice_metrics = pd.read_csv(TIMESLICE_METRICS_PATH)
    generation_qc = pd.read_csv(GENERATION_QC_PATH)
    scenario_summary = pd.read_csv(SCENARIO_SUMMARY_PATH)
    topk = pd.read_csv(TOPK_PATH, usecols=["scenario_id", "analog_distance"])

    return {
        "rain": rain,
        "x_front_km": x_front_km,
        "y_left_km": y_left_km,
        "meta": canonical,
        "timeslice_metrics": timeslice_metrics,
        "generation_qc": generation_qc,
        "scenario_summary": scenario_summary,
        "topk": topk,
        "scenario_inputs": scenario_inputs,
    }


# =========================
# Geographic backprojection
# =========================


def build_common_geo_grid(meta: pd.DataFrame) -> Dict[str, np.ndarray]:
    lon = np.asarray(normalize_lon_180(pd.to_numeric(meta["lon_180"], errors="coerce").to_numpy(dtype=np.float64)), dtype=np.float64)
    lat = pd.to_numeric(meta["lat"], errors="coerce").to_numpy(dtype=np.float64)
    if not np.isfinite(lon).all() or not np.isfinite(lat).all():
        raise RuntimeError("Cannot build geographic grid from non-finite scenario lon/lat.")
    simple_span = float(np.nanmax(lon) - np.nanmin(lon))
    if simple_span > 180.0:
        lon_min, lon_max = -180.0, 180.0
    else:
        lon_min = math.floor(float(np.nanmin(lon)) - GEO_MARGIN_DEG)
        lon_max = math.ceil(float(np.nanmax(lon)) + GEO_MARGIN_DEG)
        lon_min = max(-180.0, lon_min)
        lon_max = min(180.0, lon_max)
    lat_min = math.floor(float(np.nanmin(lat)) - GEO_MARGIN_DEG)
    lat_max = math.ceil(float(np.nanmax(lat)) + GEO_MARGIN_DEG)
    lat_min = max(-90.0, lat_min)
    lat_max = min(90.0, lat_max)
    if not (lon_min < lon_max and lat_min < lat_max):
        raise RuntimeError(f"Invalid common geographic bounds: lon=({lon_min},{lon_max}), lat=({lat_min},{lat_max})")
    lon_1d = np.round(np.arange(lon_min, lon_max + GEO_RES_DEG * 0.5, GEO_RES_DEG), 6).astype(np.float64)
    lat_1d = np.round(np.arange(lat_min, lat_max + GEO_RES_DEG * 0.5, GEO_RES_DEG), 6).astype(np.float64)
    lon_1d = np.asarray(normalize_lon_180(lon_1d), dtype=np.float64)
    lon2d, lat2d = np.meshgrid(lon_1d, lat_1d)
    area_1d = EARTH_KM_PER_DEG * GEO_RES_DEG * EARTH_KM_PER_DEG * GEO_RES_DEG * np.cos(np.deg2rad(lat_1d))
    area_1d = np.maximum(area_1d, 0.0).astype(np.float64)
    area_2d = np.repeat(area_1d[:, None], len(lon_1d), axis=1)
    return {
        "lon_1d": lon_1d,
        "lat_1d": lat_1d,
        "lon2d": lon2d,
        "lat2d": lat2d,
        "area_1d": area_1d,
        "area_2d": area_2d,
    }


def backproject_scenarios(
    rain: np.ndarray,
    meta: pd.DataFrame,
    x_front_km: np.ndarray,
    y_left_km: np.ndarray,
    geo: Mapping[str, np.ndarray],
    problem2_geo_module,
) -> Tuple[Dict[str, Dict[str, object]], pd.DataFrame]:
    lon_1d = np.asarray(geo["lon_1d"], dtype=np.float64)
    lat_1d = np.asarray(geo["lat_1d"], dtype=np.float64)
    lon2d = np.asarray(geo["lon2d"], dtype=np.float64)
    lat2d = np.asarray(geo["lat2d"], dtype=np.float64)
    area_1d = np.asarray(geo["area_1d"], dtype=np.float64)
    shape = lon2d.shape

    results: Dict[str, Dict[str, object]] = {}
    timeseries_rows: List[Dict[str, object]] = []

    for sid in SCENARIO_ORDER:
        sub = meta.loc[meta["scenario_id"] == sid].copy()
        if sub.empty:
            raise RuntimeError(f"Missing scenario rows for {sid}")
        sub = sub.sort_values("time_dt").reset_index(drop=True)
        scenario_name = str(sub["scenario_name"].iloc[0])
        cumulative = np.zeros(shape, dtype=np.float64)
        duration10 = np.zeros(shape, dtype=np.float32)
        duration20 = np.zeros(shape, dtype=np.float32)
        max_rate = np.zeros(shape, dtype=np.float32)
        qc = {"nan": 0, "inf": 0, "negative": 0, "all_zero_timeslices": 0, "sampled_points_total": 0}

        for _, row in iter_progress(list(sub.iterrows()), total=len(sub), desc=f"Backproject {sid}"):
            field_index = int(row["field_index"])
            r_geo, step_qc = problem2_geo_module.sample_storm_relative_to_geo_grid(
                rain[field_index],
                x_front_km,
                y_left_km,
                float(row["lon_180"]),
                float(row["lat"]),
                float(row["move_dir_deg"]),
                lon2d,
                lat2d,
            )
            r_geo = np.nan_to_num(r_geo, nan=0.0, posinf=0.0, neginf=0.0).astype(np.float32)
            r_geo = np.maximum(r_geo, 0.0)
            for key in ["nan", "inf", "negative"]:
                qc[key] += int(step_qc.get(key, 0))
            qc["sampled_points_total"] += int(step_qc.get("sampled_points", 0))
            if not np.any(r_geo > 0.0):
                qc["all_zero_timeslices"] += 1

            cumulative += r_geo.astype(np.float64) * HALFHOUR_HOURS
            duration10 += (r_geo >= AREA10_THRESHOLD).astype(np.float32) * HALFHOUR_HOURS
            duration20 += (r_geo >= AREA20_THRESHOLD).astype(np.float32) * HALFHOUR_HOURS
            max_rate = np.maximum(max_rate, r_geo)

            step_max, step_lon, step_lat = argmax_lon_lat(r_geo, lon_1d, lat_1d)
            timeseries_rows.append(
                {
                    "scenario_id": sid,
                    "scenario_name": scenario_name,
                    "time": pd.Timestamp(row["time_dt"]).strftime("%Y-%m-%d %H:%M:%S"),
                    "field_index": field_index,
                    "lat": float(row["lat"]),
                    "lon": float(row["lon"]),
                    "lon_180": float(row["lon_180"]),
                    "WND": float(row["WND"]),
                    "PRES": float(row["PRES"]),
                    "move_dir_deg": float(row["move_dir_deg"]),
                    "geo_rain_max_mmhr": float(step_max),
                    "geo_area10_km2": area_of_mask(r_geo >= AREA10_THRESHOLD, area_1d),
                    "geo_area20_km2": area_of_mask(r_geo >= AREA20_THRESHOLD, area_1d),
                    "geo_volume_index_halfhour_mm_km2": weighted_field_sum(r_geo * HALFHOUR_HOURS, area_1d),
                    "geo_max_rain_lon": float(step_lon),
                    "geo_max_rain_lat": float(step_lat),
                }
            )

        results[sid] = {
            "scenario_id": sid,
            "scenario_name": scenario_name,
            "track": sub,
            "accum_rain_mm": cumulative.astype(np.float32),
            "duration10_h": duration10.astype(np.float32),
            "duration20_h": duration20.astype(np.float32),
            "max_rate_mmhr": max_rate.astype(np.float32),
            "qc": qc,
        }

    return results, pd.DataFrame(timeseries_rows)


def grid_lookup_indices(source_1d: np.ndarray, target_1d: np.ndarray, axis_name: str) -> np.ndarray:
    lookup = {round(float(value), 6): i for i, value in enumerate(np.asarray(target_1d, dtype=np.float64))}
    indices: List[int] = []
    missing: List[float] = []
    for value in np.asarray(source_1d, dtype=np.float64):
        key = round(float(value), 6)
        if key not in lookup:
            missing.append(float(value))
        else:
            indices.append(int(lookup[key]))
    if missing:
        preview = ", ".join(f"{v:.6f}" for v in missing[:5])
        raise RuntimeError(f"Problem-2 KONG-REY {axis_name} grid cannot be embedded in Problem-3 common grid; missing: {preview}")
    return np.asarray(indices, dtype=int)


def embed_problem2_field(
    p2_field: np.ndarray,
    p2_lon_1d: np.ndarray,
    p2_lat_1d: np.ndarray,
    geo: Mapping[str, np.ndarray],
) -> np.ndarray:
    out = np.zeros(np.asarray(geo["lon2d"]).shape, dtype=np.float32)
    iy = grid_lookup_indices(p2_lat_1d, np.asarray(geo["lat_1d"], dtype=np.float64), "latitude")
    ix = grid_lookup_indices(p2_lon_1d, np.asarray(geo["lon_1d"], dtype=np.float64), "longitude")
    arr = np.asarray(p2_field, dtype=np.float32)
    if arr.shape != (len(iy), len(ix)):
        raise RuntimeError(f"Problem-2 KONG-REY geographic field shape {arr.shape} does not match lon/lat axes {(len(iy), len(ix))}.")
    out[np.ix_(iy, ix)] = arr
    return out


def reuse_problem2_kongrey_geographic_baseline(
    results: Dict[str, Dict[str, object]],
    geo: Mapping[str, np.ndarray],
    geo_timeseries: pd.DataFrame,
) -> Tuple[Dict[str, Dict[str, object]], pd.DataFrame, Dict[str, object]]:
    info: Dict[str, object] = {
        "status": "not_checked",
        "note": "Problem-2 KONG-REY geographic baseline was not reused.",
    }
    if not (PROBLEM2_GEO_NPZ_PATH.exists() and PROBLEM2_GEO_TIMESERIES_PATH.exists()):
        info["status"] = "missing"
        info["note"] = "Problem-2 KONG-REY geographic NPZ or timeseries table is missing."
        return results, geo_timeseries, info

    with np.load(PROBLEM2_GEO_NPZ_PATH, allow_pickle=True) as z:
        required = [
            "KONG_REY_geo_lon_1d",
            "KONG_REY_geo_lat_1d",
            "KONG_REY_geo_cumulative_rain_mm",
            "KONG_REY_geo_max_rain_mmhr",
            "KONG_REY_geo_duration10_h",
            "KONG_REY_geo_duration20_h",
        ]
        missing = [key for key in required if key not in z.files]
        if missing:
            raise RuntimeError(f"Problem-2 KONG-REY geographic NPZ missing arrays: {missing}")
        p2_lon = np.asarray(z["KONG_REY_geo_lon_1d"], dtype=np.float64)
        p2_lat = np.asarray(z["KONG_REY_geo_lat_1d"], dtype=np.float64)
        accum = embed_problem2_field(z["KONG_REY_geo_cumulative_rain_mm"], p2_lon, p2_lat, geo)
        max_rate = embed_problem2_field(z["KONG_REY_geo_max_rain_mmhr"], p2_lon, p2_lat, geo)
        d10 = embed_problem2_field(z["KONG_REY_geo_duration10_h"], p2_lon, p2_lat, geo)
        d20 = embed_problem2_field(z["KONG_REY_geo_duration20_h"], p2_lon, p2_lat, geo)

    p2_ts = pd.read_csv(PROBLEM2_GEO_TIMESERIES_PATH)
    p2_ts = p2_ts.loc[p2_ts["typhoon_name"].astype(str).eq("KONG-REY")].copy()
    p2_ts["time_dt"] = pd.to_datetime(p2_ts["time"], errors="coerce")
    s0_track = results["S0"]["track"].copy()
    s0_track["time_dt"] = pd.to_datetime(s0_track["time_dt"], errors="coerce")
    if len(p2_ts) != len(s0_track):
        info["status"] = "failed"
        info["note"] = f"Problem-2 KONG-REY geographic rows={len(p2_ts)}, S0 rows={len(s0_track)}."
        return results, geo_timeseries, info
    p2_times = p2_ts.sort_values("time_dt")["time_dt"].astype("int64").to_numpy()
    s0_times = s0_track.sort_values("time_dt")["time_dt"].astype("int64").to_numpy()
    if not np.array_equal(p2_times, s0_times):
        info["status"] = "failed"
        info["note"] = "Problem-2 KONG-REY geographic times do not match Problem-3 S0 times."
        return results, geo_timeseries, info

    s0_meta = s0_track.sort_values("time_dt").reset_index(drop=True)
    p2_ts = p2_ts.sort_values("time_dt").reset_index(drop=True)
    s0_geo_rows = pd.DataFrame(
        {
            "scenario_id": "S0",
            "scenario_name": str(results["S0"]["scenario_name"]),
            "time": s0_meta["time_dt"].dt.strftime("%Y-%m-%d %H:%M:%S"),
            "field_index": pd.to_numeric(s0_meta["field_index"], errors="coerce").astype(int),
            "lat": pd.to_numeric(s0_meta["lat"], errors="coerce"),
            "lon": pd.to_numeric(s0_meta["lon"], errors="coerce"),
            "lon_180": pd.to_numeric(s0_meta["lon_180"], errors="coerce"),
            "WND": pd.to_numeric(s0_meta["WND"], errors="coerce"),
            "PRES": pd.to_numeric(s0_meta["PRES"], errors="coerce"),
            "move_dir_deg": pd.to_numeric(s0_meta["move_dir_deg"], errors="coerce"),
            "geo_rain_max_mmhr": pd.to_numeric(p2_ts["geo_rain_max_mmhr"], errors="coerce"),
            "geo_area10_km2": pd.to_numeric(p2_ts["geo_area_10_km2"], errors="coerce"),
            "geo_area20_km2": pd.to_numeric(p2_ts["geo_area_20_km2"], errors="coerce"),
            "geo_volume_index_halfhour_mm_km2": pd.to_numeric(p2_ts["geo_volume_proxy_mm_km2"], errors="coerce"),
            "geo_max_rain_lon": pd.to_numeric(p2_ts["geo_max_rain_lon"], errors="coerce"),
            "geo_max_rain_lat": pd.to_numeric(p2_ts["geo_max_rain_lat"], errors="coerce"),
        }
    )

    updated = dict(results)
    updated["S0"] = {
        **results["S0"],
        "accum_rain_mm": accum,
        "duration10_h": d10,
        "duration20_h": d20,
        "max_rate_mmhr": max_rate,
        "qc": {
            "nan": 0,
            "inf": 0,
            "negative": 0,
            "all_zero_timeslices": 0,
            "sampled_points_total": 0,
            "source": "problem2_kongrey_geographic_baseline",
        },
    }
    out_ts = pd.concat([s0_geo_rows, geo_timeseries.loc[geo_timeseries["scenario_id"] != "S0"].copy()], ignore_index=True)
    out_ts["time"] = pd.to_datetime(out_ts["time"], errors="coerce").dt.strftime("%Y-%m-%d %H:%M:%S")
    info.update(
        {
            "status": "reused",
            "note": "S0 geographic accumulation, max rain, D10/D20 and A10/A20 timeseries directly reuse Problem-2 KONG-REY geographic baseline.",
            "reused_timesteps": int(len(s0_geo_rows)),
            "embedded_shape": str(tuple(accum.shape)),
        }
    )
    return updated, out_ts, info


# =========================
# Metrics and tables
# =========================


def summarize_topk(topk: pd.DataFrame) -> pd.DataFrame:
    return (
        topk.assign(analog_distance=pd.to_numeric(topk["analog_distance"], errors="coerce"))
        .groupby("scenario_id", as_index=False)
        .agg(
            mean_topk_distance=("analog_distance", "mean"),
            p95_topk_distance=("analog_distance", lambda s: float(np.nanpercentile(s, 95))),
        )
    )


def compute_event_metrics(
    results: Mapping[str, Mapping[str, object]],
    geo: Mapping[str, np.ndarray],
    geo_timeseries: pd.DataFrame,
    timeslice_metrics: pd.DataFrame,
    topk_summary: pd.DataFrame,
) -> pd.DataFrame:
    lon_1d = np.asarray(geo["lon_1d"], dtype=np.float64)
    lat_1d = np.asarray(geo["lat_1d"], dtype=np.float64)
    lon2d = np.asarray(geo["lon2d"], dtype=np.float64)
    lat2d = np.asarray(geo["lat2d"], dtype=np.float64)
    area_1d = np.asarray(geo["area_1d"], dtype=np.float64)
    topk_by_sid = topk_summary.set_index("scenario_id").to_dict("index")

    base_accum = np.asarray(results["S0"]["accum_rain_mm"], dtype=np.float64)
    base_d10 = np.asarray(results["S0"]["duration10_h"], dtype=np.float64)
    base_centroid_lon, base_centroid_lat = rainfall_centroid(base_accum, lon2d, lat2d, area_1d)
    base_mask_acc100 = base_accum >= 100.0
    base_mask_d10_3h = base_d10 >= 3.0

    rows: List[Dict[str, object]] = []
    for sid in SCENARIO_ORDER:
        result = results[sid]
        name = str(result["scenario_name"])
        sub_track = result["track"].copy()
        sub_geo_ts = geo_timeseries.loc[geo_timeseries["scenario_id"] == sid].copy()
        sub_slice = timeslice_metrics.loc[timeslice_metrics["scenario_id"].astype(str) == sid].copy()
        accum = np.asarray(result["accum_rain_mm"], dtype=np.float64)
        d10 = np.asarray(result["duration10_h"], dtype=np.float64)
        d20 = np.asarray(result["duration20_h"], dtype=np.float64)
        max_rate_field = np.asarray(result["max_rate_mmhr"], dtype=np.float64)
        max_accum, max_lon, max_lat = argmax_lon_lat(accum, lon_1d, lat_1d)
        max_rate, _, _ = argmax_lon_lat(max_rate_field, lon_1d, lat_1d)
        centroid_lon, centroid_lat = rainfall_centroid(accum, lon2d, lat2d, area_1d)
        centroid_shift = 0.0 if sid == "S0" else haversine_km(base_centroid_lon, base_centroid_lat, centroid_lon, centroid_lat)
        topk_row = topk_by_sid.get(sid, {})
        row = {
            "scenario_id": sid,
            "scenario_name": name,
            "n_timesteps": int(len(sub_track)),
            "start_time": pd.Timestamp(sub_track["time_dt"].min()).strftime("%Y-%m-%d %H:%M:%S"),
            "end_time": pd.Timestamp(sub_track["time_dt"].max()).strftime("%Y-%m-%d %H:%M:%S"),
            "max_accum_rain_mm": float(max_accum),
            "max_accum_lon": float(max_lon),
            "max_accum_lat": float(max_lat),
            "max_rain_rate_mmhr": float(max_rate),
            "max_p95_mmhr": float(pd.to_numeric(sub_slice["p95_mmhr"], errors="coerce").max()),
            "max_p99_mmhr": float(pd.to_numeric(sub_slice["p99_mmhr"], errors="coerce").max()),
            "max_area10_km2": float(pd.to_numeric(sub_geo_ts["geo_area10_km2"], errors="coerce").max()),
            "max_area20_km2": float(pd.to_numeric(sub_geo_ts["geo_area20_km2"], errors="coerce").max()),
            "mean_area10_km2": float(pd.to_numeric(sub_geo_ts["geo_area10_km2"], errors="coerce").mean()),
            "mean_area20_km2": float(pd.to_numeric(sub_geo_ts["geo_area20_km2"], errors="coerce").mean()),
            "geo_D10_max_h": float(np.nanmax(d10)),
            "geo_D20_max_h": float(np.nanmax(d20)),
            "area_accum_ge_100mm_km2": area_of_mask(accum >= 100.0, area_1d),
            "area_accum_ge_250mm_km2": area_of_mask(accum >= 250.0, area_1d),
            "area_D10_ge_3h_km2": area_of_mask(d10 >= 3.0, area_1d),
            "area_D10_ge_6h_km2": area_of_mask(d10 >= 6.0, area_1d),
            "rainfall_centroid_lon": float(centroid_lon),
            "rainfall_centroid_lat": float(centroid_lat),
            "rainfall_centroid_shift_km_vs_S0": float(centroid_shift),
            "IoU_accum_ge_100mm_vs_S0": 1.0 if sid == "S0" else weighted_iou(accum >= 100.0, base_mask_acc100, area_1d),
            "IoU_D10_ge_3h_vs_S0": 1.0 if sid == "S0" else weighted_iou(d10 >= 3.0, base_mask_d10_3h, area_1d),
            "total_event_rain_volume_index": weighted_field_sum(accum, area_1d),
            "dominant_quadrant_mode": dominant_mode(sub_slice.get("dominant_quadrant", pd.Series(dtype=str))),
            "mean_topk_distance": float(topk_row.get("mean_topk_distance", np.nan)),
            "p95_topk_distance": float(topk_row.get("p95_topk_distance", np.nan)),
            "qc_level": "PENDING",
            "interpretation_note": "",
        }
        rows.append(row)
    metrics = pd.DataFrame(rows)
    return metrics


def make_relative_changes(metrics: pd.DataFrame) -> pd.DataFrame:
    base = metrics.loc[metrics["scenario_id"] == "S0"].iloc[0].to_dict()
    rows: List[Dict[str, object]] = []
    for _, row in metrics.iterrows():
        sid = str(row["scenario_id"])
        if sid == "S0":
            main_sensitive = "baseline"
            explanation = "Reference scenario; deltas are zero by definition."
        elif sid == "S1":
            main_sensitive = "rain-rate tail and heavy-rain area"
            explanation = "WND enhancement and synchronous PRES reduction mainly alter intensity-sensitive rainfall extremes."
        elif sid == "S2":
            main_sensitive = "geographic rain footprint"
            explanation = "Westward/near-coast path displacement moves the fixed-location exposure pattern relative to S0."
        elif sid == "S3":
            main_sensitive = "coastal impact location"
            explanation = "Localized nearshore path perturbation shifts the affected belt without changing the full storm history."
        elif sid == "S4":
            main_sensitive = "accumulation and duration"
            explanation = "Slower translation increases residence time, so fixed-location accumulation and D10 exposure respond strongly."
        else:
            main_sensitive = "compound risk"
            explanation = "Moderate intensity, path, and speed perturbations jointly affect rate, footprint, and duration."
        rows.append(
            {
                "scenario_id": sid,
                "scenario_name": row["scenario_name"],
                "delta_max_accum_rain_pct": 0.0 if sid == "S0" else pct_change(row["max_accum_rain_mm"], base["max_accum_rain_mm"]),
                "delta_max_rain_rate_pct": 0.0 if sid == "S0" else pct_change(row["max_rain_rate_mmhr"], base["max_rain_rate_mmhr"]),
                "delta_max_p99_pct": 0.0 if sid == "S0" else pct_change(row["max_p99_mmhr"], base["max_p99_mmhr"]),
                "delta_max_area10_pct": 0.0 if sid == "S0" else pct_change(row["max_area10_km2"], base["max_area10_km2"]),
                "delta_max_area20_pct": 0.0 if sid == "S0" else pct_change(row["max_area20_km2"], base["max_area20_km2"]),
                "delta_geo_D10_max_pct": 0.0 if sid == "S0" else pct_change(row["geo_D10_max_h"], base["geo_D10_max_h"]),
                "delta_area_accum_ge_100mm_pct": 0.0 if sid == "S0" else pct_change(row["area_accum_ge_100mm_km2"], base["area_accum_ge_100mm_km2"]),
                "delta_area_D10_ge_3h_pct": 0.0 if sid == "S0" else pct_change(row["area_D10_ge_3h_km2"], base["area_D10_ge_3h_km2"]),
                "delta_total_event_rain_volume_pct": 0.0 if sid == "S0" else pct_change(row["total_event_rain_volume_index"], base["total_event_rain_volume_index"]),
                "main_sensitive_output": main_sensitive,
                "main_physical_explanation": explanation,
            }
        )
    return pd.DataFrame(rows)


def brief_conclusion(row: pd.Series, rel_row: pd.Series) -> str:
    sid = str(row["scenario_id"])
    if sid == "S0":
        return "直接复用问题二 KONG-REY calibrated/geographic 基准。"
    if sid == "S1":
        return f"强度增强主要抬升雨强尾部，P99 变化 {rel_row['delta_max_p99_pct']:.1f}%."
    if sid == "S2":
        return f"路径近岸改变落区重叠，累计雨区 IoU 为 {row['IoU_accum_ge_100mm_vs_S0']:.2f}."
    if sid == "S3":
        return f"近岸段偏移主要转移沿海影响带，质心偏移 {row['rainfall_centroid_shift_km_vs_S0']:.1f} km."
    if sid == "S4":
        return f"移速减慢显著放大滞留效应，D10 变化 {rel_row['delta_geo_D10_max_pct']:.1f}%."
    return f"复合扰动同步改变强度、落区和持续时间，总量指数变化 {rel_row['delta_total_event_rain_volume_pct']:.1f}%."


def make_final_and_sensitivity_tables(metrics: pd.DataFrame, rel_changes: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    rel_by_sid = rel_changes.set_index("scenario_id")
    comparison_rows = []
    for _, row in metrics.iterrows():
        rel_row = rel_by_sid.loc[row["scenario_id"]]
        comparison_rows.append(
            {
                "scenario_id": row["scenario_id"],
                "scenario_name": row["scenario_name"],
                "max_accum_rain_mm": row["max_accum_rain_mm"],
                "max_rain_rate_mmhr": row["max_rain_rate_mmhr"],
                "max_p99_mmhr": row["max_p99_mmhr"],
                "max_area10_km2": row["max_area10_km2"],
                "geo_D10_max_h": row["geo_D10_max_h"],
                "area_accum_ge_100mm_km2": row["area_accum_ge_100mm_km2"],
                "area_D10_ge_3h_km2": row["area_D10_ge_3h_km2"],
                "rainfall_centroid_shift_km_vs_S0": row["rainfall_centroid_shift_km_vs_S0"],
                "IoU_accum_ge_100mm_vs_S0": row["IoU_accum_ge_100mm_vs_S0"],
                "delta_max_accum_rain_pct": rel_row["delta_max_accum_rain_pct"],
                "delta_max_area10_pct": rel_row["delta_max_area10_pct"],
                "delta_geo_D10_max_pct": rel_row["delta_geo_D10_max_pct"],
                "brief_conclusion": brief_conclusion(row, rel_row),
            }
        )
    comparison = pd.DataFrame(comparison_rows)

    sens_rows: List[Dict[str, object]] = []
    metrics_by_sid = metrics.set_index("scenario_id")
    for sid in ["S1", "S2", "S3", "S4", "S5"]:
        row = metrics_by_sid.loc[sid]
        rel = rel_by_sid.loc[sid]
        if sid == "S1":
            control = "Intensity enhancement"
            candidates = {
                "max_rain_rate": rel["delta_max_rain_rate_pct"],
                "P99": rel["delta_max_p99_pct"],
                "area10": rel["delta_max_area10_pct"],
                "area20": rel["delta_max_area20_pct"],
            }
            explanation = "Higher WND with lower PRES changes the intensity-sensitive rain-rate tail and heavy-rain footprint."
            sentence = f"S1 mainly modifies rainfall intensity; P99 changes by {rel['delta_max_p99_pct']:.1f}% relative to S0."
        elif sid == "S2":
            control = "Near-coast/westward path shift"
            candidates = {
                "centroid_shift_km": row["rainfall_centroid_shift_km_vs_S0"],
                "1-IoU_accum100": 100.0 * (1.0 - row["IoU_accum_ge_100mm_vs_S0"]),
                "area_accum100": rel["delta_area_accum_ge_100mm_pct"],
            }
            explanation = "Track displacement changes where the storm-relative rain shield is projected on the fixed map."
            sentence = f"S2 changes the geographic footprint; the accum>=100 mm IoU versus S0 is {row['IoU_accum_ge_100mm_vs_S0']:.2f}."
        elif sid == "S3":
            control = "Nearshore segment/landfall shift"
            candidates = {
                "centroid_shift_km": row["rainfall_centroid_shift_km_vs_S0"],
                "1-IoU_D10_3h": 100.0 * (1.0 - row["IoU_D10_ge_3h_vs_S0"]),
                "area_D10_3h": rel["delta_area_D10_ge_3h_pct"],
            }
            explanation = "A localized path perturbation transfers the coastal impact belt while retaining the broader storm evolution."
            sentence = f"S3 relocates nearshore exposure; the rainfall centroid shifts {row['rainfall_centroid_shift_km_vs_S0']:.1f} km."
        elif sid == "S4":
            control = "Slower translation"
            candidates = {
                "max_accum": rel["delta_max_accum_rain_pct"],
                "geo_D10_max": rel["delta_geo_D10_max_pct"],
                "area_D10_3h": rel["delta_area_D10_ge_3h_pct"],
            }
            explanation = "Reduced translation speed extends exposure time at fixed locations, amplifying accumulation and D10 duration."
            sentence = f"S4 is most interpretable as a residence-time scenario; geo D10 changes by {rel['delta_geo_D10_max_pct']:.1f}%."
        else:
            control = "Compound moderate high-risk perturbation"
            candidates = {
                "max_accum": rel["delta_max_accum_rain_pct"],
                "area10": rel["delta_max_area10_pct"],
                "volume": rel["delta_total_event_rain_volume_pct"],
                "geo_D10": rel["delta_geo_D10_max_pct"],
            }
            explanation = "Moderate intensity, path, and speed perturbations combine rate, footprint, and residence-time effects."
            sentence = f"S5 combines multiple controls; total rainfall volume index changes by {rel['delta_total_event_rain_volume_pct']:.1f}%."
        clean_candidates = {k: abs(float(v)) for k, v in candidates.items() if np.isfinite(float(v))}
        metric = max(clean_candidates, key=clean_candidates.get) if clean_candidates else "NA"
        observed = candidates.get(metric, np.nan)
        sens_rows.append(
            {
                "scenario_id": sid,
                "control_factor": control,
                "most_sensitive_metric": metric,
                "observed_change": observed,
                "physical_explanation": explanation,
                "paper_sentence": sentence,
            }
        )
    sensitivity = pd.DataFrame(sens_rows)
    return comparison, sensitivity


SCENARIO_CN_NAMES = {
    "S0": "问题二基准",
    "S1": "强度增强",
    "S2": "路径近岸/西移",
    "S3": "近岸段偏移",
    "S4": "移动速度减慢",
    "S5": "复合高风险",
}


def latex_escape(value: object) -> str:
    text = "" if pd.isna(value) else str(value)
    text = text.replace("\\", "<<<BACKSLASH>>>")
    replacements = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = text.replace("<<<BACKSLASH>>>", r"\textbackslash{}")
    return text


def write_problem3_latex_tables(comparison: pd.DataFrame) -> None:
    PROBLEM3_TABLE_DIR.mkdir(parents=True, exist_ok=True)
    work = comparison.copy()
    work["scenario_id"] = work["scenario_id"].astype(str)
    work = work.set_index("scenario_id").loc[SCENARIO_ORDER].reset_index()

    compact_lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\small",
        r"\caption{S0--S5 虚拟台风情景事件级核心指标与相对变化}",
        r"\label{tab:problem3_scenario_comparison}",
        r"\resizebox{\textwidth}{!}{",
        r"\begin{tabular}{c l r r r r r r p{4.3cm}}",
        r"\hline",
        r"情景 & 情景名称 & 最大累计/mm & 最大$A_{10}$/km$^2$ & 最大$D_{10}$/h & $\Delta C_{\max}$/\% & $\Delta A_{10}$/\% & $\Delta D_{10}$/\% & 简要结论 \\",
        r"\hline",
    ]
    for _, row in work.iterrows():
        sid = str(row["scenario_id"])
        compact_lines.append(
            f"{sid} & {latex_escape(SCENARIO_CN_NAMES.get(sid, row['scenario_name']))} & "
            f"{float(row['max_accum_rain_mm']):.2f} & "
            f"{float(row['max_area10_km2']):.2f} & "
            f"{float(row['geo_D10_max_h']):.1f} & "
            f"{float(row['delta_max_accum_rain_pct']):.2f} & "
            f"{float(row['delta_max_area10_pct']):.2f} & "
            f"{float(row['delta_geo_D10_max_pct']):.2f} & "
            f"{latex_escape(row['brief_conclusion'])} \\\\"
        )
    compact_lines.extend([r"\hline", r"\end{tabular}", r"}", r"\end{table}", ""])
    COMPACT_MAIN_TABLE_PATH.write_text("\n".join(compact_lines), encoding="utf-8")

    paper_lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{虚拟台风情景事件级降水指标及相对基准变化}",
        r"\label{tab:problem3_scenario_comparison_full}",
        r"\begin{tabular}{c l r r r r r r r}",
        r"\hline",
        r"情景 & 情景含义 & 最大累计/mm & 最大雨强/(mm h$^{-1}$) & P99/(mm h$^{-1}$) & 最大$A_{10}$/km$^2$ & 最大$D_{10}$/h & $\Delta C_{\max}$/\% & $\Delta A_{10}$/\% \\",
        r"\hline",
    ]
    for _, row in work.iterrows():
        sid = str(row["scenario_id"])
        paper_lines.append(
            f"{sid} & {latex_escape(SCENARIO_CN_NAMES.get(sid, row['scenario_name']))} & "
            f"{float(row['max_accum_rain_mm']):.2f} & "
            f"{float(row['max_rain_rate_mmhr']):.2f} & "
            f"{float(row['max_p99_mmhr']):.2f} & "
            f"{float(row['max_area10_km2']):.2f} & "
            f"{float(row['geo_D10_max_h']):.1f} & "
            f"{float(row['delta_max_accum_rain_pct']):.2f} & "
            f"{float(row['delta_max_area10_pct']):.2f} \\\\"
        )
    paper_lines.extend([r"\hline", r"\end{tabular}", r"\end{table}", ""])
    PAPER_SCENARIO_LATEX_TABLE_PATH.write_text("\n".join(paper_lines), encoding="utf-8")


def compare_s0_with_problem2_baseline(metrics: pd.DataFrame) -> Dict[str, object]:
    out = {
        "status": "not_found",
        "note": "Problem-2 geographic baseline files were not found.",
        "problem2_max_accum_rain_mm": np.nan,
        "problem3_s0_max_accum_rain_mm": np.nan,
        "max_accum_abs_diff_mm": np.nan,
        "max_accum_location_shift_km": np.nan,
        "problem2_geo_D10_max_h": np.nan,
        "problem3_s0_geo_D10_max_h": np.nan,
        "geo_D10_abs_diff_h": np.nan,
        "problem2_max_area10_km2": np.nan,
        "problem3_s0_max_area10_km2": np.nan,
        "max_area10_rel_diff_pct": np.nan,
        "problem2_volume_index": np.nan,
        "problem3_s0_volume_index": np.nan,
        "volume_rel_diff_pct": np.nan,
    }
    if not (PROBLEM2_GEO_SUMMARY_PATH.exists() and PROBLEM2_GEO_TIMESERIES_PATH.exists()):
        return out
    p2_summary = pd.read_csv(PROBLEM2_GEO_SUMMARY_PATH)
    p2_ts = pd.read_csv(PROBLEM2_GEO_TIMESERIES_PATH)
    p2_row = p2_summary.loc[p2_summary["typhoon_name"].astype(str).eq("KONG-REY")]
    p2_ts = p2_ts.loc[p2_ts["typhoon_name"].astype(str).eq("KONG-REY")]
    if p2_row.empty or p2_ts.empty:
        out["note"] = "Problem-2 geographic files exist, but KONG-REY rows were not found."
        return out
    s0 = metrics.loc[metrics["scenario_id"] == "S0"].iloc[0]
    p2 = p2_row.iloc[0]
    p2_max_accum = float(p2["geo_max_cumulative_rain_mm"])
    p3_max_accum = float(s0["max_accum_rain_mm"])
    loc_shift = haversine_km(
        float(p2["geo_max_cumulative_rain_lon"]),
        float(p2["geo_max_cumulative_rain_lat"]),
        float(s0["max_accum_lon"]),
        float(s0["max_accum_lat"]),
    )
    p2_d10 = float(p2["geo_max_duration10_h"])
    p3_d10 = float(s0["geo_D10_max_h"])
    p2_area10 = float(pd.to_numeric(p2_ts["geo_area_10_km2"], errors="coerce").max())
    p3_area10 = float(s0["max_area10_km2"])
    p2_volume = float(pd.to_numeric(p2_ts["geo_volume_proxy_mm_km2"], errors="coerce").sum())
    p3_volume = float(s0["total_event_rain_volume_index"])
    accum_rel = abs(p3_max_accum - p2_max_accum) / max(abs(p2_max_accum), EPS)
    d10_abs = abs(p3_d10 - p2_d10)
    area_rel = abs(p3_area10 - p2_area10) / max(abs(p2_area10), EPS)
    volume_rel = abs(p3_volume - p2_volume) / max(abs(p2_volume), EPS)
    if accum_rel <= 0.05 and d10_abs <= 3.0 and area_rel <= 0.10 and volume_rel <= 0.10:
        status = "PASS"
        note = "S0 event metrics are close to the Problem-2 KONG-REY geographic baseline."
    elif accum_rel <= 0.20 and d10_abs <= 10.0 and area_rel <= 0.25 and volume_rel <= 0.25:
        status = "WARNING-but-usable"
        note = "S0 differs from the Problem-2 baseline but remains usable; Step-2 already recorded non-identical S0 fields."
    else:
        status = "WARNING"
        note = "S0 differs clearly from the Problem-2 baseline; use the unified Problem-3 S0 as the scenario control."
    out.update(
        {
            "status": status,
            "note": note,
            "problem2_max_accum_rain_mm": p2_max_accum,
            "problem3_s0_max_accum_rain_mm": p3_max_accum,
            "max_accum_abs_diff_mm": float(abs(p3_max_accum - p2_max_accum)),
            "max_accum_location_shift_km": float(loc_shift),
            "problem2_geo_D10_max_h": p2_d10,
            "problem3_s0_geo_D10_max_h": p3_d10,
            "geo_D10_abs_diff_h": float(d10_abs),
            "problem2_max_area10_km2": p2_area10,
            "problem3_s0_max_area10_km2": p3_area10,
            "max_area10_rel_diff_pct": pct_change(p3_area10, p2_area10),
            "problem2_volume_index": p2_volume,
            "problem3_s0_volume_index": p3_volume,
            "volume_rel_diff_pct": pct_change(p3_volume, p2_volume),
        }
    )
    return out


def build_step3_qc(
    results: Mapping[str, Mapping[str, object]],
    geo: Mapping[str, np.ndarray],
    generation_qc: pd.DataFrame,
    baseline: Mapping[str, object],
    figure_paths: Sequence[Path],
) -> pd.DataFrame:
    area_valid = bool(np.isfinite(geo["area_1d"]).all() and np.all(np.asarray(geo["area_1d"]) > 0.0))
    expected_figure_count = 15
    all_figures_ok = len(figure_paths) >= expected_figure_count and all(Path(p).exists() for p in figure_paths)
    gen_qc = generation_qc.set_index("scenario_id").to_dict("index")
    rows: List[Dict[str, object]] = []
    for sid in SCENARIO_ORDER:
        result = results[sid]
        accum = np.asarray(result["accum_rain_mm"], dtype=np.float64)
        d10 = np.asarray(result["duration10_h"], dtype=np.float64)
        d20 = np.asarray(result["duration20_h"], dtype=np.float64)
        invalid_accum = int(np.count_nonzero(np.isnan(accum)) + np.count_nonzero(np.isinf(accum)))
        negative_accum = int(np.count_nonzero(np.isfinite(accum) & (accum < 0.0)))
        accum_all_zero = bool(np.nanmax(accum) <= 0.0)
        dur_all_zero = bool(np.nanmax(d10) <= 0.0 and np.nanmax(d20) <= 0.0)
        notes: List[str] = []
        level = "PASS"
        if invalid_accum > 0 or negative_accum > 0:
            level = "FAIL"
            notes.append("accumulation contains invalid or negative values")
        if accum.shape != np.asarray(geo["lon2d"]).shape or d10.shape != accum.shape:
            level = "FAIL"
            notes.append("geographic array shape mismatch")
        if accum_all_zero or dur_all_zero:
            level = "FAIL"
            notes.append("accumulation or duration result is all zero")
        if not area_valid:
            level = "FAIL"
            notes.append("latitude-corrected grid area is invalid")
        if not all_figures_ok:
            level = "FAIL"
            notes.append("required figures were not all generated")
        inherited = gen_qc.get(sid, {}).get("qc_level", "")
        inherited_note = gen_qc.get(sid, {}).get("qc_note", "")
        if level != "FAIL":
            if str(inherited).upper() == "WARNING":
                level = "WARNING"
                notes.append(f"step2_qc_warning:{inherited_note}")
            if sid == "S0" and str(baseline.get("status")) not in {"PASS", "not_found"}:
                level = "WARNING"
                notes.append(f"baseline_consistency:{baseline.get('status')}")
        rows.append(
            {
                "scenario_id": sid,
                "n_timesteps": int(len(result["track"])),
                "accum_shape": str(accum.shape),
                "duration_shape": str(d10.shape),
                "nan_count_accum": int(np.count_nonzero(np.isnan(accum))),
                "inf_count_accum": int(np.count_nonzero(np.isinf(accum))),
                "negative_count_accum": negative_accum,
                "max_accum_rain_mm": float(np.nanmax(accum)),
                "max_duration10_h": float(np.nanmax(d10)),
                "area_grid_valid": area_valid,
                "same_colorbar_ready": all_figures_ok,
                "geographic_projection_status": "completed_common_0.1deg_grid",
                "baseline_consistency_status": str(baseline.get("status")) if sid == "S0" else "not_applicable",
                "qc_level": level,
                "qc_note": "; ".join(notes) if notes else "Step-3 metrics quality checks passed.",
            }
        )
    return pd.DataFrame(rows)


def add_interpretation_and_qc(metrics: pd.DataFrame, qc: pd.DataFrame, rel_changes: pd.DataFrame) -> pd.DataFrame:
    qc_by_sid = qc.set_index("scenario_id")
    rel_by_sid = rel_changes.set_index("scenario_id")
    out = metrics.copy()
    notes = []
    levels = []
    for _, row in out.iterrows():
        sid = str(row["scenario_id"])
        levels.append(qc_by_sid.loc[sid, "qc_level"])
        if sid == "S0":
            note = "Baseline control scenario for all relative changes."
        elif sid == "S1":
            note = f"Intensity enhancement: max rain rate delta {rel_by_sid.loc[sid, 'delta_max_rain_rate_pct']:.1f}%."
        elif sid == "S2":
            note = f"Near-coast path shift: accum>=100 mm IoU {row['IoU_accum_ge_100mm_vs_S0']:.2f}."
        elif sid == "S3":
            note = f"Nearshore segment shift: centroid shift {row['rainfall_centroid_shift_km_vs_S0']:.1f} km."
        elif sid == "S4":
            note = f"Slower translation: geo D10 delta {rel_by_sid.loc[sid, 'delta_geo_D10_max_pct']:.1f}%."
        else:
            note = f"Compound scenario: volume index delta {rel_by_sid.loc[sid, 'delta_total_event_rain_volume_pct']:.1f}%."
        notes.append(note)
    out["qc_level"] = levels
    out["interpretation_note"] = notes
    return out


# =========================
# Saving arrays and figures
# =========================


def save_geographic_npz(results: Mapping[str, Mapping[str, object]], geo: Mapping[str, np.ndarray]) -> None:
    accum = np.stack([np.asarray(results[sid]["accum_rain_mm"], dtype=np.float32) for sid in SCENARIO_ORDER], axis=0)
    d10 = np.stack([np.asarray(results[sid]["duration10_h"], dtype=np.float32) for sid in SCENARIO_ORDER], axis=0)
    d20 = np.stack([np.asarray(results[sid]["duration20_h"], dtype=np.float32) for sid in SCENARIO_ORDER], axis=0)
    np.savez_compressed(
        GEOGRAPHIC_NPZ_PATH,
        scenario_id=np.asarray(SCENARIO_ORDER),
        scenario_name=np.asarray([str(results[sid]["scenario_name"]) for sid in SCENARIO_ORDER]),
        lon_grid=np.asarray(geo["lon2d"], dtype=np.float32),
        lat_grid=np.asarray(geo["lat2d"], dtype=np.float32),
        lon_1d=np.asarray(geo["lon_1d"], dtype=np.float32),
        lat_1d=np.asarray(geo["lat_1d"], dtype=np.float32),
        accum_rain_mm=accum,
        duration10_h=d10,
        duration20_h=d20,
        grid_area_km2=np.asarray(geo["area_2d"], dtype=np.float32),
        GEO_RES_DEG=np.asarray(GEO_RES_DEG, dtype=np.float32),
        HALF_HOUR_ACCUMULATION_FACTOR=np.asarray(HALFHOUR_HOURS, dtype=np.float32),
    )


def cartopy_available(problem2_geo_module) -> bool:
    try:
        return bool(problem2_geo_module.cartopy_local_features_available())
    except Exception:
        return False


def setup_axes(fig, extent: Sequence[float], use_cartopy: bool, problem2_geo_module):
    if use_cartopy:
        try:
            return problem2_geo_module.setup_geo_axes(fig, extent, True)
        except Exception:
            pass
    ax = fig.add_subplot(1, 1, 1)
    ax.set_xlim(extent[0], extent[1])
    ax.set_ylim(extent[2], extent[3])
    ax.set_xlabel("longitude")
    ax.set_ylabel("latitude")
    ax.grid(True, linewidth=0.35, linestyle="--", alpha=0.35)
    return ax, None


def plot_track_and_centroid(ax, track: pd.DataFrame, centroid_lon: float, centroid_lat: float, transform=None) -> None:
    kwargs = {"transform": transform} if transform is not None else {}
    lon = pd.to_numeric(track["lon_180"], errors="coerce").to_numpy(dtype=np.float64)
    lat = pd.to_numeric(track["lat"], errors="coerce").to_numpy(dtype=np.float64)
    ax.plot(lon, lat, color="black", linewidth=1.2, alpha=0.85, zorder=5, **kwargs)
    ax.scatter(lon[0], lat[0], marker="s", s=42, color="#2ca25f", edgecolor="black", linewidth=0.4, zorder=6, **kwargs)
    ax.scatter(lon[-1], lat[-1], marker="X", s=48, color="#de2d26", edgecolor="black", linewidth=0.4, zorder=6, **kwargs)
    if np.isfinite(centroid_lon) and np.isfinite(centroid_lat):
        ax.scatter(
            centroid_lon,
            centroid_lat,
            marker="*",
            s=115,
            color="#ffbf00",
            edgecolor="black",
            linewidth=0.55,
            zorder=7,
            **kwargs,
        )


def make_map_figures(
    results: Mapping[str, Mapping[str, object]],
    metrics: pd.DataFrame,
    geo: Mapping[str, np.ndarray],
    problem2_geo_module,
) -> List[Path]:
    PROBLEM3_FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    lon_1d = np.asarray(geo["lon_1d"], dtype=np.float64)
    lat_1d = np.asarray(geo["lat_1d"], dtype=np.float64)
    extent = [float(lon_1d.min()), float(lon_1d.max()), float(lat_1d.min()), float(lat_1d.max())]
    use_cartopy = cartopy_available(problem2_geo_module)
    metrics_by_sid = metrics.set_index("scenario_id")
    vmax_accum = max(float(np.nanmax(results[sid]["accum_rain_mm"])) for sid in SCENARIO_ORDER)
    vmax_duration = max(float(np.nanmax(results[sid]["duration10_h"])) for sid in SCENARIO_ORDER)
    vmax_accum = max(vmax_accum, 1.0)
    vmax_duration = max(vmax_duration, 1.0)
    paths: List[Path] = []

    for sid in SCENARIO_ORDER:
        result = results[sid]
        name = str(result["scenario_name"])
        for key, stem, title, unit, cmap, vmax in [
            ("accum_rain_mm", "accum_rain", "Accumulated rainfall", "mm", "YlGnBu", vmax_accum),
            ("duration10_h", "duration10", "Duration >=10 mm/hr", "h", "plasma", vmax_duration),
        ]:
            field = np.asarray(result[key], dtype=np.float64)
            fig = plt.figure(figsize=(9.5, 7.2))
            ax, proj = setup_axes(fig, extent, use_cartopy, problem2_geo_module)
            mesh_kwargs = {"transform": proj} if proj is not None else {}
            im = ax.pcolormesh(lon_1d, lat_1d, field, cmap=cmap, shading="auto", vmin=0.0, vmax=vmax, zorder=2, **mesh_kwargs)
            mrow = metrics_by_sid.loc[sid]
            plot_track_and_centroid(
                ax,
                result["track"],
                float(mrow["rainfall_centroid_lon"]),
                float(mrow["rainfall_centroid_lat"]),
                transform=proj,
            )
            ax.set_title(f"{sid} {name} - {title}")
            cbar = fig.colorbar(im, ax=ax, shrink=0.82, pad=0.04)
            cbar.set_label(unit)
            path = PROBLEM3_FIGURE_DIR / f"problem3_{stem}_{sid}.png"
            fig.savefig(path, dpi=240, bbox_inches="tight")
            plt.close(fig)
            paths.append(path)
    return paths


def make_metric_bar_figures(metrics: pd.DataFrame, rel_changes: pd.DataFrame, results: Mapping[str, Mapping[str, object]], geo: Mapping[str, np.ndarray], problem2_geo_module) -> List[Path]:
    PROBLEM3_FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    paths: List[Path] = []
    ids = metrics["scenario_id"].astype(str).tolist()

    fig, axes = plt.subplots(1, 3, figsize=(14.5, 4.6), constrained_layout=True)
    specs = [
        ("max_accum_rain_mm", "Max accumulation (mm)"),
        ("max_area10_km2", "Max A10 (km$^2$)"),
        ("geo_D10_max_h", "Max D10 (h)"),
    ]
    for ax, (col, ylabel) in zip(axes, specs):
        ax.bar(ids, pd.to_numeric(metrics[col], errors="coerce"), color="#4C78A8")
        ax.set_ylabel(ylabel)
        ax.set_xlabel("scenario")
        ax.grid(axis="y", linewidth=0.35, linestyle="--", alpha=0.35)
    path = PROBLEM3_FIGURE_DIR / "problem3_scenario_metric_bars.png"
    fig.savefig(path, dpi=240, bbox_inches="tight")
    plt.close(fig)
    paths.append(path)

    rel_plot = rel_changes.loc[rel_changes["scenario_id"] != "S0"].copy()
    fig, ax = plt.subplots(figsize=(10.2, 5.6), constrained_layout=True)
    width = 0.18
    x = np.arange(len(rel_plot))
    rel_specs = [
        ("delta_max_accum_rain_pct", "max accum"),
        ("delta_max_area10_pct", "max A10"),
        ("delta_geo_D10_max_pct", "D10 max"),
        ("delta_total_event_rain_volume_pct", "volume"),
    ]
    for offset, (col, label) in zip(np.linspace(-1.5 * width, 1.5 * width, len(rel_specs)), rel_specs):
        ax.bar(x + offset, pd.to_numeric(rel_plot[col], errors="coerce"), width=width, label=label)
    ax.axhline(0.0, color="black", linewidth=0.7)
    ax.set_xticks(x)
    ax.set_xticklabels(rel_plot["scenario_id"])
    ax.set_ylabel("Change vs S0 (%)")
    ax.set_xlabel("scenario")
    ax.grid(axis="y", linewidth=0.35, linestyle="--", alpha=0.35)
    ax.legend(ncol=2, frameon=False)
    path = PROBLEM3_FIGURE_DIR / "problem3_relative_change_bars.png"
    fig.savefig(path, dpi=240, bbox_inches="tight")
    plt.close(fig)
    paths.append(path)

    lon_1d = np.asarray(geo["lon_1d"], dtype=np.float64)
    lat_1d = np.asarray(geo["lat_1d"], dtype=np.float64)
    extent = [float(lon_1d.min()), float(lon_1d.max()), float(lat_1d.min()), float(lat_1d.max())]
    use_cartopy = cartopy_available(problem2_geo_module)
    fig = plt.figure(figsize=(9.7, 7.2))
    ax, proj = setup_axes(fig, extent, use_cartopy, problem2_geo_module)
    colors = {"S0": "#1f77b4", "S1": "#ff7f0e", "S2": "#2ca02c", "S3": "#d62728", "S4": "#9467bd", "S5": "#8c564b"}
    kwargs_base = {"transform": proj} if proj is not None else {}
    for sid in SCENARIO_ORDER:
        track = results[sid]["track"]
        lon = pd.to_numeric(track["lon_180"], errors="coerce").to_numpy(dtype=np.float64)
        lat = pd.to_numeric(track["lat"], errors="coerce").to_numpy(dtype=np.float64)
        ax.plot(lon, lat, color=colors[sid], linewidth=1.4, alpha=0.85, label=sid, zorder=4, **kwargs_base)
        mrow = metrics.loc[metrics["scenario_id"] == sid].iloc[0]
        ax.scatter(
            float(mrow["rainfall_centroid_lon"]),
            float(mrow["rainfall_centroid_lat"]),
            marker="*",
            s=95,
            color=colors[sid],
            edgecolor="black",
            linewidth=0.45,
            zorder=6,
            **kwargs_base,
        )
    ax.set_title("Problem 3 scenario paths and rainfall centroids")
    ax.legend(loc="best", frameon=True, framealpha=0.85)
    path = PROBLEM3_FIGURE_DIR / "problem3_path_and_centroid_shift.png"
    fig.savefig(path, dpi=240, bbox_inches="tight")
    plt.close(fig)
    paths.append(path)
    return paths


# =========================
# Report
# =========================


def write_report(
    inputs: Mapping[str, object],
    geo: Mapping[str, np.ndarray],
    metrics: pd.DataFrame,
    rel_changes: pd.DataFrame,
    comparison: pd.DataFrame,
    sensitivity: pd.DataFrame,
    qc: pd.DataFrame,
    baseline: Mapping[str, object],
    figure_paths: Sequence[Path],
    use_cartopy: bool,
    final_status: str,
) -> None:
    rain = np.asarray(inputs["rain"])
    lon_1d = np.asarray(geo["lon_1d"], dtype=np.float64)
    lat_1d = np.asarray(geo["lat_1d"], dtype=np.float64)
    lines: List[str] = [
        "# Problem 3 Step 3 Event Metrics Report",
        "",
        "## 1. Inputs read",
        f"- Calibrated scenario rainfields: `{rel(CALIBRATED_NPZ_PATH)}`",
        f"- Timeslice metrics: `{rel(TIMESLICE_METRICS_PATH)}`",
        f"- Step-2 generation QC: `{rel(GENERATION_QC_PATH)}`",
        f"- Top-K analog table: `{rel(TOPK_PATH)}`",
        f"- Scenario input table: `{rel(SCENARIO_INPUT_PATH)}`",
        f"- Scenario summary table: `{rel(SCENARIO_SUMMARY_PATH)}`",
        f"- Problem-2 geographic logic reused from: `{rel(PROBLEM2_GEO_SCRIPT)}`",
        f"- Storm-relative x/y grid read from: `{rel(PROBLEM2_EOF_MODEL_PATH)}`",
        "",
        "## 2. Geographic backprojection",
        "- Geographic backprojection was performed because the Step-2 fields are storm-relative 201 x 201 grids centered on the typhoon.",
        "- The reverse-sampling formula and `RegularGridInterpolator` logic follow the Problem-2 geographic backprojection script.",
        f"- Common geographic grid: lon {float(lon_1d.min()):.1f} to {float(lon_1d.max()):.1f}, lat {float(lat_1d.min()):.1f} to {float(lat_1d.max()):.1f}.",
        f"- Resolution: {GEO_RES_DEG} deg x {GEO_RES_DEG} deg; grid shape: {np.asarray(geo['lon2d']).shape}.",
        "- Grid-cell area uses latitude correction: 111.32^2 x 0.1 x 0.1 x cos(lat), in km2.",
        f"- Cartopy/Natural Earth overlay used: `{use_cartopy}`. If false, metrics and maps still use the fixed lon-lat grid.",
        "",
        "## 3. Unit conversion",
        "- The rainfields are rainfall intensity fields in mm/hr.",
        "- Half-hour rainfall is H_t(i,j) = 0.5 x R_t(i,j).",
        "- Event accumulation is C(i,j) = 0.5 x sum_t R_t(i,j).",
        "- Fixed-grid duration is D10(i,j) = 0.5 x sum_t 1{R_t(i,j) >= 10 mm/hr}; D20 is defined analogously.",
        "- This script never directly sums mm/hr as mm.",
        "",
        "## 4. Scenario event metrics",
        markdown_table(
            metrics,
            [
                "scenario_id",
                "n_timesteps",
                "max_accum_rain_mm",
                "max_area10_km2",
                "geo_D10_max_h",
                "area_accum_ge_100mm_km2",
                "total_event_rain_volume_index",
                "qc_level",
            ],
        ),
        "",
        "## 5. Relative changes vs S0",
        markdown_table(
            rel_changes,
            [
                "scenario_id",
                "delta_max_accum_rain_pct",
                "delta_max_area10_pct",
                "delta_geo_D10_max_pct",
                "delta_total_event_rain_volume_pct",
                "main_sensitive_output",
            ],
        ),
        "",
        "## 6. S0 baseline consistency check",
        f"- Status: `{baseline.get('status')}`",
        f"- Note: {baseline.get('note')}",
        f"- Problem-2 KONG-REY max accumulation: {float(baseline.get('problem2_max_accum_rain_mm', np.nan)):.3f} mm.",
        f"- Problem-3 S0 max accumulation: {float(baseline.get('problem3_s0_max_accum_rain_mm', np.nan)):.3f} mm.",
        f"- Max-accumulation location shift: {float(baseline.get('max_accum_location_shift_km', np.nan)):.3f} km.",
        f"- Problem-2 / Problem-3 S0 geo D10 max: {float(baseline.get('problem2_geo_D10_max_h', np.nan)):.3f} / {float(baseline.get('problem3_s0_geo_D10_max_h', np.nan)):.3f} h.",
        f"- Problem-2 / Problem-3 S0 max area10: {float(baseline.get('problem2_max_area10_km2', np.nan)):.3f} / {float(baseline.get('problem3_s0_max_area10_km2', np.nan)):.3f} km2.",
        "- S0 is required to reuse the finalized Problem-2 KONG-REY geographic baseline before relative changes are computed.",
        "",
        "## 7. Physical interpretation",
        markdown_table(sensitivity),
        "",
        "## 8. Sensitivity summary",
        "- S1 is read through intensity-sensitive metrics: max rain rate, P99, area10, and area20.",
        "- S2 is read through geographic footprint metrics: rainfall centroid shift, IoU, and area with accumulation >=100 mm.",
        "- S3 is read through relocation of the nearshore impact belt and centroid/IoU changes.",
        "- S4 is read through residence-time metrics: max accumulation, geo_D10_max, and area_D10_ge_3h.",
        "- S5 is read as the compound case; it should be described by which of rate, footprint, duration, and volume jointly increase.",
        "",
        "## 9. QC status",
        markdown_table(qc, ["scenario_id", "n_timesteps", "max_accum_rain_mm", "max_duration10_h", "baseline_consistency_status", "qc_level", "qc_note"]),
        f"- Calibrated rainfield shape read: `{rain.shape}`.",
        f"- Figures generated: {len(figure_paths)}.",
        f"- Final run status: **{final_status}**.",
        "",
        "## 10. Outputs",
        f"- Event metrics: `{rel(EVENT_METRICS_PATH)}`",
        f"- Relative changes: `{rel(RELATIVE_CHANGES_PATH)}`",
        f"- Geographic accumulation/duration NPZ: `{rel(GEOGRAPHIC_NPZ_PATH)}`",
        f"- Final comparison table: `{rel(FINAL_COMPARISON_TABLE_PATH)}`",
        f"- Sensitivity interpretation table: `{rel(SENSITIVITY_TABLE_PATH)}`",
        f"- Compact LaTeX table: `{rel(COMPACT_MAIN_TABLE_PATH)}`",
        f"- Step-3 QC: `{rel(STEP3_QC_PATH)}`",
        f"- Figures directory: `{rel(PROBLEM3_FIGURE_DIR)}`",
        "",
        "## 11. Next step",
        "- Step 4 should select the formal tables and maps, then write the Problem-3 paper text around the S0-controlled scenario comparison.",
        "- The report text should explicitly distinguish fixed-geographic accumulation/duration maps from storm-relative structure maps.",
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


# =========================
# Main
# =========================


def main() -> None:
    ensure_dirs()
    problem2_geo_module = load_problem2_geo_module()

    print("[31] Loading Problem-3 Step-2 rainfields and metadata")
    inputs = load_inputs()
    rain = np.asarray(inputs["rain"], dtype=np.float32)
    meta = inputs["meta"].copy()
    print(f"[31] Calibrated rainfield shape: {rain.shape}")

    counts = meta.groupby("scenario_id").size().reindex(SCENARIO_ORDER).fillna(0).astype(int)
    for sid, expected in EXPECTED_COUNTS.items():
        actual = int(counts.loc[sid])
        if actual != expected:
            raise RuntimeError(f"{sid} timestep count mismatch: actual={actual}, expected={expected}")

    print("[31] Building common geographic grid and backprojecting S0-S5")
    geo = build_common_geo_grid(meta)
    results, geo_timeseries = backproject_scenarios(
        rain,
        meta,
        np.asarray(inputs["x_front_km"], dtype=np.float64),
        np.asarray(inputs["y_left_km"], dtype=np.float64),
        geo,
        problem2_geo_module,
    )
    results, geo_timeseries, geo_reuse = reuse_problem2_kongrey_geographic_baseline(results, geo, geo_timeseries)
    print(f"[31] S0 geographic baseline reuse: {geo_reuse['status']} - {geo_reuse['note']}")

    print("[31] Computing event metrics and relative changes")
    topk_summary = summarize_topk(inputs["topk"])
    metrics = compute_event_metrics(results, geo, geo_timeseries, inputs["timeslice_metrics"], topk_summary)
    rel_changes = make_relative_changes(metrics)
    baseline = compare_s0_with_problem2_baseline(metrics)

    print("[31] Saving geographic arrays and drawing figures")
    save_geographic_npz(results, geo)
    geo_timeseries.to_csv(GEOGRAPHIC_TIMESERIES_PATH, index=False)
    use_cartopy = cartopy_available(problem2_geo_module)
    figure_paths: List[Path] = []
    figure_paths.extend(make_map_figures(results, metrics, geo, problem2_geo_module))
    figure_paths.extend(make_metric_bar_figures(metrics, rel_changes, results, geo, problem2_geo_module))

    print("[31] Building QC, comparison tables, and report")
    qc = build_step3_qc(results, geo, inputs["generation_qc"], baseline, figure_paths)
    metrics = add_interpretation_and_qc(metrics, qc, rel_changes)
    rel_changes = make_relative_changes(metrics)
    comparison, sensitivity = make_final_and_sensitivity_tables(metrics, rel_changes)

    metrics.to_csv(EVENT_METRICS_PATH, index=False)
    rel_changes.to_csv(RELATIVE_CHANGES_PATH, index=False)
    qc.to_csv(STEP3_QC_PATH, index=False)
    comparison.to_csv(FINAL_COMPARISON_TABLE_PATH, index=False)
    sensitivity.to_csv(SENSITIVITY_TABLE_PATH, index=False)
    write_problem3_latex_tables(comparison)

    final_status = "SUCCESS"
    if (qc["qc_level"] == "FAIL").any():
        final_status = "FAIL"
    elif (qc["qc_level"] == "WARNING").any():
        final_status = "WARNING"

    write_report(
        inputs,
        geo,
        metrics,
        rel_changes,
        comparison,
        sensitivity,
        qc,
        baseline,
        figure_paths,
        use_cartopy,
        final_status,
    )

    print("\n========== Problem-3 Step-3 event metrics complete ==========")
    print(f"Calibrated rainfield shape: {rain.shape}")
    print(f"Scenario IDs: {SCENARIO_ORDER}")
    print("Scenario timesteps:")
    print(counts.to_string())
    print(f"0.5-hour accumulation conversion applied: True")
    print(f"Geographic backprojection applied: True")
    print(f"Event metrics output: {rel(EVENT_METRICS_PATH)}")
    print(f"Relative changes output: {rel(RELATIVE_CHANGES_PATH)}")
    print(f"Geographic NPZ output: {rel(GEOGRAPHIC_NPZ_PATH)}")
    print(f"Final comparison table output: {rel(FINAL_COMPARISON_TABLE_PATH)}")
    print(f"Compact LaTeX table output: {rel(COMPACT_MAIN_TABLE_PATH)}")
    print(f"Figures generated: {len(figure_paths)}")
    print(f"Report output: {rel(REPORT_PATH)}")
    print("Per-scenario QC level:")
    print(qc[["scenario_id", "qc_level", "qc_note"]].to_string(index=False))
    print(f"Final status: {final_status}")


if __name__ == "__main__":
    main()
